### ISSUE TITLE
WooCommerce integration example

### ISSUE THREAD

**Issue by sla-te** [mushroomlabs/hub20#129]
I'm interested in implementing this gateway to my shop, which uses WooCommerce because BTCPays support for ETH is kind of broken for good, because the dev who created it literally disappeared and since then its not functional and not maintained anymore.

I couldn't find anything related to WooCommerce and hub20 yet though and am thinking that I would probably have to write a complete WC-API based implementation to make this work, or do I?

**Comment by lullis** [comment]
Hi @sla-te. 

To be frank, I haven't started yet to work on different integrations besides the [Javascript Checkout Widget](https://gitlab.com/mushroomlabs/hub20/checkout20), but I definitely would  like to have integrations with WooCommerce/Shopify/Magento.

Have you looked into the documentation page? You can start [here](https://docs.hub20.io/tutorials/payment_gateway/) and you can see also see the existing [REST API](https://docs.hub20.io/reference/api/).

I'll close the issue, but please do follow up either on the [discussions page](https://github.com/mushroomlabs/hub20/discussions) or on the [Matrix space](https://matrix.to/#/#hub20:communick.com).


Let me know if that helps.
